CREATE TABLE
    "AUTHOR" (
        "AUTHOR_ID" NUMBER (10, 0),
        "FULL_NAME" VARCHAR2 (100) NOT NULL ENABLE,
        "BIO" VARCHAR2 (1000),
        CONSTRAINT "PK_AUTHOR" PRIMARY KEY ("AUTHOR_ID") ENABLE
    );