CREATE TABLE
    "BOOK_AUTHOR" (
        "ISBN" VARCHAR2 (13),
        "AUTHOR_ID" NUMBER (10, 0),
        CONSTRAINT "PK_BOOK_AUTHOR" PRIMARY KEY ("ISBN", "AUTHOR_ID") ENABLE
    );

ALTER TABLE "BOOK_AUTHOR" ADD CONSTRAINT "FK_BA_AUTHOR" FOREIGN KEY ("AUTHOR_ID") REFERENCES "AUTHOR" ("AUTHOR_ID") ENABLE;

ALTER TABLE "BOOK_AUTHOR" ADD CONSTRAINT "FK_BA_ISBN" FOREIGN KEY ("ISBN") REFERENCES "BOOK" ("ISBN") ON DELETE CASCADE ENABLE;