CREATE TABLE
    "BOOK" (
        "ISBN" VARCHAR2 (13),
        "TITLE" VARCHAR2 (255) NOT NULL ENABLE,
        "PUB_ID" NUMBER (5, 0),
        "PUB_YEAR" NUMBER (4, 0),
        "EDITION" NUMBER (2, 0) DEFAULT 1,
        CONSTRAINT "CHK_ISBN_FORMAT" CHECK (REGEXP_LIKE (ISBN, '^(97(8|9))?\d{9}(\d|X)$')) ENABLE,
        CONSTRAINT "PK_BOOK" PRIMARY KEY ("ISBN") ENABLE
    );

ALTER TABLE "BOOK" ADD CONSTRAINT "FK_BOOK_PUB" FOREIGN KEY ("PUB_ID") REFERENCES "PUBLISHER" ("PUB_ID") ENABLE;