CREATE TABLE
    "BOOK_COPY" (
        "COPY_ID" NUMBER (12, 0),
        "ISBN" VARCHAR2 (13) NOT NULL ENABLE,
        "SHELF_ID" NUMBER (4, 0) NOT NULL ENABLE,
        "STATUS" VARCHAR2 (20) DEFAULT 'AVAILABLE',
        CONSTRAINT "CHK_COPY_STATUS" CHECK (
            STATUS IN (
                'AVAILABLE',
                'ISSUED',
                'LOST',
                'MAINTENANCE',
                'RESERVED'
            )
        ) ENABLE,
        CONSTRAINT "PK_COPY" PRIMARY KEY ("COPY_ID") ENABLE
    );

ALTER TABLE "BOOK_COPY" ADD CONSTRAINT "FK_COPY_ISBN" FOREIGN KEY ("ISBN") REFERENCES "BOOK" ("ISBN") ENABLE;

ALTER TABLE "BOOK_COPY" ADD CONSTRAINT "FK_COPY_SHELF" FOREIGN KEY ("SHELF_ID") REFERENCES "SHELF" ("SHELF_ID") ENABLE;