CREATE TABLE
    "FINE" (
        "FINE_ID" NUMBER (15, 0),
        "TRANS_ID" NUMBER (15, 0) NOT NULL ENABLE,
        "AMOUNT" NUMBER (8, 2) NOT NULL ENABLE,
        "PAID_STATUS" VARCHAR2 (10) DEFAULT 'UNPAID',
        "PAY_DATE" DATE,
        CONSTRAINT "CHK_FINE_STATUS" CHECK (PAID_STATUS IN ('PAID', 'UNPAID')) ENABLE,
        CONSTRAINT "PK_FINE" PRIMARY KEY ("FINE_ID") ENABLE
    );

ALTER TABLE "FINE" ADD CONSTRAINT "FK_FINE_LOAN" FOREIGN KEY ("TRANS_ID") REFERENCES "LOAN_TRANSACTION" ("TRANS_ID") ENABLE;