CREATE TABLE  "LOAN_TRANSACTION" 
   (	"TRANS_ID" NUMBER(15,0), 
	"COPY_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"MEMBER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ISSUE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DUE_DATE" DATE NOT NULL ENABLE, 
	"RETURN_DATE" DATE, 
	"STATUS" VARCHAR2(10) DEFAULT 'OPEN', 
	 CONSTRAINT "CHK_LOAN_STATUS" CHECK (STATUS IN ('OPEN', 'CLOSED')) ENABLE, 
	 CONSTRAINT "PK_LOAN" PRIMARY KEY ("TRANS_ID") ENABLE
   ) ;ALTER TABLE  "LOAN_TRANSACTION" ADD CONSTRAINT "FK_LOAN_COPY" FOREIGN KEY ("COPY_ID")
	  REFERENCES  "BOOK_COPY" ("COPY_ID") ENABLE;ALTER TABLE  "LOAN_TRANSACTION" ADD CONSTRAINT "FK_LOAN_MEMBER" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES  "MEMBER" ("MEMBER_ID") ENABLE;

CREATE OR REPLACE TRIGGER  "TRG_ENFORCE_LOAN_LIMIT" 
BEFORE INSERT ON LOAN_TRANSACTION
FOR EACH ROW
DECLARE
    v_current_loans NUMBER;
    v_max_allowed NUMBER;
BEGIN
    SELECT mt.MAX_BOOKS 
    INTO v_max_allowed
    FROM MEMBER m
    JOIN MEMBERSHIP_TYPE mt ON m.TYPE_ID = mt.TYPE_ID
    WHERE m.MEMBER_ID = :NEW.MEMBER_ID;

    SELECT COUNT(*)
    INTO v_current_loans
    FROM LOAN_TRANSACTION
    WHERE MEMBER_ID = :NEW.MEMBER_ID AND STATUS = 'OPEN';

    IF v_current_loans >= v_max_allowed THEN
        RAISE_APPLICATION_ERROR(-20001, 
            'Borrowing limit reached. Member cannot borrow more than ' || v_max_allowed || ' items.');
    END IF;
END;

ALTER TRIGGER  "TRG_ENFORCE_LOAN_LIMIT" ENABLE;

CREATE OR REPLACE TRIGGER  "TRG_SYNC_BOOK_STATUS" 
AFTER INSERT OR UPDATE ON LOAN_TRANSACTION
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE BOOK_COPY
        SET STATUS = 'ISSUED'
        WHERE COPY_ID = :NEW.COPY_ID;
        
    ELSIF UPDATING AND :NEW.STATUS = 'CLOSED' THEN
        UPDATE BOOK_COPY
        SET STATUS = 'AVAILABLE'
        WHERE COPY_ID = :NEW.COPY_ID;
    END IF;
END;
/
ALTER TRIGGER  "TRG_SYNC_BOOK_STATUS" ENABLE;
