CREATE TABLE
    "MEMBERSHIP_TYPE" (
        "TYPE_ID" NUMBER (2, 0),
        "TYPE_NAME" VARCHAR2 (20) NOT NULL ENABLE,
        "MAX_BOOKS" NUMBER (2, 0) NOT NULL ENABLE,
        "LOAN_DAYS" NUMBER (3, 0) NOT NULL ENABLE,
        "DAILY_FINE" NUMBER (5, 2) DEFAULT 0.00 NOT NULL ENABLE,
        CONSTRAINT "CHK_MAX_BOOKS" CHECK (MAX_BOOKS > 0) ENABLE,
        CONSTRAINT "CHK_LOAN_DAYS" CHECK (LOAN_DAYS > 0) ENABLE,
        CONSTRAINT "PK_MEM_TYPE" PRIMARY KEY ("TYPE_ID") ENABLE,
        CONSTRAINT "UQ_TYPE_NAME" UNIQUE ("TYPE_NAME") ENABLE
    );