CREATE TABLE
    "MEMBER" (
        "MEMBER_ID" NUMBER (10, 0),
        "NAME" VARCHAR2 (100) NOT NULL ENABLE,
        "EMAIL" VARCHAR2 (100) NOT NULL ENABLE,
        "PHONE" VARCHAR2 (15) NOT NULL ENABLE,
        "TYPE_ID" NUMBER (2, 0) NOT NULL ENABLE,
        "STATUS" VARCHAR2 (10) DEFAULT 'ACTIVE',
        "REG_DATE" DATE DEFAULT SYSDATE,
        CONSTRAINT "CHK_MEM_STATUS" CHECK (STATUS IN ('ACTIVE', 'SUSPENDED', 'EXPIRED')) ENABLE,
        CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBER_ID") ENABLE,
        CONSTRAINT "UQ_MEM_EMAIL" UNIQUE ("EMAIL") ENABLE
    );

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_MEM_TYPE" FOREIGN KEY ("TYPE_ID") REFERENCES "MEMBERSHIP_TYPE" ("TYPE_ID") ENABLE;