SELECT 
    s.CATEGORY,
    COUNT(l.TRANS_ID) AS CIRCULATION_COUNT,
    ROUND(RATIO_TO_REPORT(COUNT(l.TRANS_ID)) OVER () * 100, 2) AS PERCENTAGE_SHARE
FROM LOAN_TRANSACTION l
JOIN BOOK_COPY bc ON l.COPY_ID = bc.COPY_ID
JOIN SHELF s ON bc.SHELF_ID = s.SHELF_ID
GROUP BY s.CATEGORY
ORDER BY CIRCULATION_COUNT DESC;
