CREATE TABLE
    "PUBLISHER" (
        "PUB_ID" NUMBER (5, 0),
        "PUB_NAME" VARCHAR2 (100) NOT NULL ENABLE,
        "ADDRESS" VARCHAR2 (255),
        "CONTACT_NO" VARCHAR2 (20),
        CONSTRAINT "PK_PUB" PRIMARY KEY ("PUB_ID") ENABLE,
        CONSTRAINT "UQ_PUB_NAME" UNIQUE ("PUB_NAME") ENABLE
    );