CREATE TABLE
    "RESERVATION" (
        "RES_ID" NUMBER (10, 0),
        "ISBN" VARCHAR2 (13) NOT NULL ENABLE,
        "MEMBER_ID" NUMBER (10, 0) NOT NULL ENABLE,
        "RES_DATE" DATE DEFAULT SYSDATE,
        "STATUS" VARCHAR2 (20) DEFAULT 'PENDING',
        CHECK (STATUS IN ('PENDING', 'FULFILLED', 'CANCELLED')) ENABLE,
        PRIMARY KEY ("RES_ID") ENABLE
    );

ALTER TABLE "RESERVATION" ADD FOREIGN KEY ("ISBN") REFERENCES "BOOK" ("ISBN") ENABLE;

ALTER TABLE "RESERVATION" ADD FOREIGN KEY ("MEMBER_ID") REFERENCES "MEMBER" ("MEMBER_ID") ENABLE;