CREATE TABLE
    "SHELF" (
        "SHELF_ID" NUMBER (4, 0),
        "FLOOR_NO" NUMBER (2, 0) NOT NULL ENABLE,
        "AISLE_CODE" VARCHAR2 (5) NOT NULL ENABLE,
        "CATEGORY" VARCHAR2 (50) NOT NULL ENABLE,
        CONSTRAINT "PK_SHELF" PRIMARY KEY ("SHELF_ID") ENABLE
    );