CREATE OR REPLACE TRIGGER TRG_SYNC_BOOK_STATUS
AFTER INSERT OR UPDATE ON LOAN_TRANSACTION
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        -- Mark copy as ISSUED upon new loan creation
        UPDATE BOOK_COPY
        SET STATUS = 'ISSUED'
        WHERE COPY_ID = :NEW.COPY_ID;
        
    ELSIF UPDATING AND :NEW.STATUS = 'CLOSED' THEN
        -- Mark copy as AVAILABLE upon loan closure
        UPDATE BOOK_COPY
        SET STATUS = 'AVAILABLE'
        WHERE COPY_ID = :NEW.COPY_ID;
    END IF;
END;
