CREATE
OR REPLACE VIEW VIEW_FINANCIAL_DEFAULTERS AS
SELECT
    m.MEMBER_ID,
    m.NAME,
    m.EMAIL,
    SUM(f.AMOUNT) AS TOTAL_UNPAID_FINE
FROM
    MEMBER m
    JOIN LOAN_TRANSACTION l ON m.MEMBER_ID = l.MEMBER_ID
    JOIN FINE f ON l.TRANS_ID = f.TRANS_ID
WHERE
    f.PAID_STATUS = 'UNPAID'
GROUP BY
    m.MEMBER_ID,
    m.NAME,
    m.EMAIL
HAVING
    SUM(f.AMOUNT) > 0
ORDER BY
    TOTAL_UNPAID_FINE DESC;