CREATE
OR REPLACE VIEW VIEW_OVERDUE_ALERTS AS
SELECT
    l.TRANS_ID,
    m.MEMBER_ID,
    m.NAME AS MEMBER_NAME,
    m.EMAIL,
    b.TITLE,
    l.ISSUE_DATE,
    l.DUE_DATE,
    TRUNC (SYSDATE - l.DUE_DATE) AS DAYS_OVERDUE
FROM
    LOAN_TRANSACTION l
    JOIN MEMBER m ON l.MEMBER_ID = m.MEMBER_ID
    JOIN BOOK_COPY bc ON l.COPY_ID = bc.COPY_ID
    JOIN BOOK b ON bc.ISBN = b.ISBN
WHERE
    l.STATUS = 'OPEN'
    AND l.DUE_DATE < SYSDATE;